### ISSUE TITLE
The default configuration file is overwritten when the program is run

### ISSUE THREAD

**Issue by uxbug** [projectdiscovery/alterx#217] opened 2024-11-11 14:54 UTC
- alterx version v0.0.4
- macos
- go version go1.23.0 darwin/arm64

after mod default config file, then run alterx.
config file is restored to the default state by alterx.

`~/.config/alterx/permutation_v0.0.4.yaml`

**Comment by uxbug** [comment] 2024-11-11 15:04
It may be a yaml configuration error. I hope it can support prompting configuration file errors instead of directly overwriting the modified configuration file.

**Comment by dogancanbakir** [comment] 2024-11-12 10:14
Couldn't repro it, this is what I did:

before --showing only the modified part!
```console
$ cat /Users/dogancanbakir/Library/Application\ Support/alterx/config.yaml
...

# max export data size (kb, mb, gb, tb) (default mb)
max-size: 1

...
```

```console
$ echo scanme.sh | alterx

   ___   ____          _  __
  / _ | / / /____ ____| |/_/
 / __ |/ / __/ -_) __/>  <  
/_/ |_/_/\__/\__/_/ /_/|_|                               

                projectdiscovery.io

[INF] Current alterx version v0.0.4 (latest)
eng.scanme.sh
compute.scanme.sh
data.scanme.sh
...
[INF] Generated 111 permutations in 0.0004s
```


after --showing only the modified part!
```console
$ cat /Users/dogancanbakir/Library/Application\ Support/alterx/config.yaml
...

# max export data size (kb, mb, gb, tb) (default mb)
max-size: 1

...
```

**Comment by uxbug** [comment] 2024-11-12 10:53
> It may be a yaml configuration error. I hope it can support prompting configuration file errors instead of directly overwriting the modified configuration file.

Sorry, I realized later that it was a misconfiguration of the yaml format that led to the. (It may be indentation.)

**Comment by dogancanbakir** [comment] 2024-11-12 11:50
@uxbug I understand this, as the problem is solved for you. I am closing this. Feel free to reopen if that's not the case.

**Closed by dogancanbakir** 2024-11-12 11:50 UTC
